from typing import Tuple

CELL_SIZE = 21
CELL_HALF_SIZE = CELL_SIZE / 2

GRID_ROWS_COUNT = 31
GRID_COLUMNS_COUNT = 31
GRID_SIZE = (GRID_COLUMNS_COUNT, GRID_ROWS_COUNT)
GRID_CENTER = (int(GRID_COLUMNS_COUNT / 2), int(GRID_ROWS_COUNT / 2))

SCREEN_START_POINT = (0, 0)
SCREEN_WIDTH = CELL_SIZE * GRID_COLUMNS_COUNT
SCREEN_HEIGHT = CELL_SIZE * GRID_ROWS_COUNT
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)

FPS = 60

CELL_RECT_SIDE = 4
MAIN_DIRECTORY = 'D:\Projects\PYTHON\PacmanByMobik'


class COLORS():
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    BLUE = (0, 0, 255)
    GRAY = (125, 125, 125)
    LIGHT_BLUE = (64, 128, 255)
    YELLOW = (225, 225, 0)
    PINK = (230, 50, 230)
    TRANSPARENT = (0, 0, 0, 0)


class CELL_TYPE():
    MAP_WALL = (0, 0, 255, 255)
    MAP_ROAD = (0, 0, 0, 255)
    MAP_CROSSROAD = (0, 255, 0, 255)
    MAP_PACMAN_START_POSITION = (255, 255, 0, 255)
    MAP_GHOSTS_START_POSITION = (255, 0, 255, 255)
    MAP_SPIRIT_DOOR = (255, 0, 0, 255)
    MAP_REST_SPACE = (255, 255, 255, 255)


class DIRECTIONS():
    UP = 1
    RIGHT = 2
    DOWN = 3
    LEFT = 4

class VECTORS():
    VECTOR_UP = (0, -1)
    VECTOR_DOWN = (0, 1)
    VECTOR_RIGHT = (1, 0)
    VECTOR_LEFT = (-1, 0)

class MOVABLE_ENTITIES():
    PACMAN = 1
    GHOST_RIKKO = 2
    GHOST_GREENKY = 3
    GHOST_PINKY = 4
    GHOST_CLYNE = 5

class ALGORITHMES():
    BFS = 0
    DFS = 1
    UCS = 2
    BFS_STR = "BFS"
    DFS_STR = "DFS"
    UCS_STR = "UCS"

class SPRITE_TYPES():
    PACMAN = 1
    GHOST = 2
    COIN = 3
    CELL_WALL = 4
    CELL_ROAD = 5
    CELL_CROSSROAD = 6
    CELL_DOOR = 7

class UI_TEXT_OBJECTS():
    GAME_OVER_MARKER = 0
    HP_MARKER = 1
    SCORE_MARKER = 2
    CURRENT_ALGORITHM_MARKER = 3
